name: MkDocs Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
    
jobs:
  linters:
    name: Repository linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b                    # @v4.1.4
      - name: Install NodeJs                                                               # Install Software NodeJs 
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8                  # @v4.0.2
        with:
          node-version: 16
      - name: Install repo-linter
        run: |
          npm install -g repolinter
      - name: Run Repo Linter
        run: |
          repolinter --rulesetFile cfg/repolint.json lint .      
  
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e6dab246340401bf53eec993b8f05aebe80ac636
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: cfg/gitleaks.toml
          
  build:
    name: MkDocs Github Pages automatic deployment
    runs-on: ubuntu-latest
    needs: 
      - linters 
      - scan
    steps:
      - name: Checkout main
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Set up Python 3.9
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: MkDocs gh-deploy
        run: |
          git pull
          mkdocs gh-deploy -v
