name: MkDocs Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
    
jobs:
  linters:
    name: Repository linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f                    # @v4.1.3
      - name: Install NodeJs                                                               # Install Software NodeJs 
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c                  # @v3.6.0
        with:
          node-version: 16
      - name: Install repo-linter
        run: |
          npm install -g repolinter
      - name: Run Repo Linter
        run: |
          repolinter --rulesetFile cfg/repolint.json lint .      
  
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e6dab246340401bf53eec993b8f05aebe80ac636
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: cfg/gitleaks.toml
          
  build:
    name: MkDocs Github Pages automatic deployment
    runs-on: ubuntu-latest
    needs: 
      - linters 
      - scan
    steps:
      - name: Checkout main
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f

      - name: Set up Python 3.9
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: MkDocs gh-deploy
        run: |
          git pull
          mkdocs gh-deploy -v
