name: MkDocs Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
    
jobs:
  linters:
    name: Repository linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871                    # @v4.2.1
      - name: Install NodeJs                                                               # Install Software NodeJs 
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af                  # @v4.1.0
        with:
          node-version: 16
      - name: Install repo-linter
        run: |
          npm install -g repolinter
      - name: Run Repo Linter
        run: |
          repolinter --rulesetFile cfg/repolint.json lint .      
  
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@44c470ffc35caa8b1eb3e8012ca53c2f9bea4eb5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: cfg/gitleaks.toml
          
  build:
    name: MkDocs Github Pages automatic deployment
    runs-on: ubuntu-latest
    needs: 
      - linters 
      - scan
    steps:
      - name: Checkout main
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Set up Python 3.9
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: MkDocs gh-deploy
        run: |
          git pull
          mkdocs gh-deploy -v
